version: '3.8'
services:
  l4d2:
    restart: "no"
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "27015:27015/udp" # game port
      - "27015:27015/tcp" # rcon port
    secrets:
      - rcon_password
    #--------
    # you can customise the install by loading out
    # volumes for some of the program folders:
    # example, uncomment to enable:

    #volumes:
    #  - ./left4dead2/cfg/custom/:/customfiles/left4dead2/cfg/custom/:ro
    #  - ./left4dead2/addons/:/customfiles/left4dead2/addons/:ro

    #--------

    # example overrides using envs
    environment:
    # Specificy custom auto exec and server files
    #  - SRCDS_AUTOEXEC="custom/autoexec.cfg"
    #  - SRCDS_SERVERCFG="custom/server.cfg"
    # sv_fpsmax
    #  - SRCDS_FPSMAX="300"
    # custom port number, should match ports in ports section
    #  - SRCDS_PORT="27015"
    # override external ip
    #  - SRCDS_NET_PUBLIC_ADDRESS="0"
    # sv_lan
      - SRCDS_LAN="0"
    # maxplayers
      - SRCDS_MAXPLAYERS=8
    # sv_setsteamaccount , not used by l4d2
    #  - SRCDS_TOKEN=0
    # rcon_password, better to use secrets.
    #  - SRCDS_RCONPW="changeme"
    # client password
    #  - SRCDS_PW=""
    # sv_region
      - SRCDS_REGION=3
    # hostname
      - SRCDS_HOSTNAME="New L4d2 Server"

secrets:
  rcon_password:
    file: secrets/rconpassword.txt